WebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace IanByrne.ResearchProject.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApp/Pages/Index.cshtml.cs
using System;
using System.Linq;
using System.Net.Sockets;
using IanByrne.ResearchProject.Database;
using IanByrne.ResearchProject.Shared;
using IanByrne.ResearchProject.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace IanByrne.ResearchProject.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly PostMortemContext _context;

        public IndexModel(ILogger<IndexModel> logger, PostMortemContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {

        }

        public PartialViewResult OnGetSurveyModalPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_SurveyModalPartial",
                ViewData = new ViewDataDictionary<Survey>(ViewData, new Survey { })
            };
        }

        public PartialViewResult OnGetParticipantInformationModalPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_ParticipantInformationModalPartial"
            };
        }

        public ActionResult OnPostSendMessageToChatScript(SendMessageRequest request)
        {
            var response = new SendMessageResponse();

            try
            {
                var tcpClient = new TcpClient("localhost", 1024);
                using (ITcpClient client = new TcpClientHandler(tcpClient))
                {
                    var chatScript = new ChatScriptHandler(client);

                    response = chatScript.SendMessage(request, _context);
                }
            }
            catch (Exception ex)
            {
                response.Messages = new string[] { ex.Message };
            }

            string responseJson = JsonConvert.SerializeObject(response);

            return Content(responseJson);
        }

        public ActionResult OnPostEnsureUserCreated(User user)
        {
            user.EnsureCreated(_context);

            return new NoContentResult();
        }

        public ActionResult OnPostGetUserFromCookieId(string id)
        {
            try
            {
                Guid idGuid;

                if (!Guid.TryParse(id, out idGuid))
                {
                    return new NotFoundResult();
                }

                var user = _context
                    .Users
                    .Include(u => u.Survey)
                    .Include(u => u.Objectives)
                    .SingleOrDefault(u => u.CookieId == idGuid);

                string responseJson = JsonConvert.SerializeObject(user, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

                return Content(responseJson);
            }
            catch
            {
                return new NotFoundResult();
            }
        }

        public ActionResult OnPostSaveUser(User user)
        {
            if (user != null)
            {
                user.Save(_context);
            }

            return new NoContentResult();
        }

        public ActionResult OnPostSetWinTime(User user)
        {
            if (user != null && user.WinDateTime == null)
            {
                user.WinDateTime = DateTime.UtcNow;
                user.Save(_context);
            }

            string userJson = JsonConvert.SerializeObject(user, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

            return Content(userJson);
        }

        public PartialViewResult OnPostSurveyModalPartial(Survey survey)
        {
            if(ModelState.IsValid)
            {
                var user = _context
                    .Users
                    .Include(u => u.Survey)
                    .SingleOrDefault(u => u.CookieId == survey.User.CookieId);

                if (user != null && user.Survey == null)
                {
                    user.Survey = survey;
                    _context.SaveChanges();
                }
            }

            return new PartialViewResult()
            {
                ViewName = "_SurveyModalPartial",
                ViewData = new ViewDataDictionary<Survey>(ViewData, survey)
            };
        }
    }
}

WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
}

<div class="text-center">
    <h1 class="display-4">Post Mortem</h1>
    <img id="loader" src="~/loader.gif" />
    <iframe id="game" name="game" src="~/export/index.html"></iframe>
    <span class="AntiForge"> @Html.AntiForgeryToken() </span>
</div>
<div id="participantInfoFooter" class="text-center">
    <p>
        <a href="#" onclick="ShowParticipantInformationModal()">Participant Information</a>
    </p>
</div>

<div id="modal-container"></div>

WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Post Mortem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/js.cookie.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Pages/_ParticipantInformationModalPartial.cshtml
@using IanByrne.ResearchProject.Shared.Models

<div class="modal fade" id="participantInformation" tabindex="-1" role="dialog" aria-labelledby="participantLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="participantLabel">Participant Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    This game is part of a research study. Before you decide whether you would like to take part it is important that you
                    understand why the research is being done and what it would involve for you. Please take time to read the following
                    information carefully.
                </p>

                <h4>What is the purpose of the study?</h4>
                <p>
                    This is a study to measure player immersion in games. Data will be collected from participants over several weeks
                    before being collated, analysed, and published as part of a post graduate dissertation assignment due in Dec 2020.
                </p>

                <h4>Why have I been invited to take part?</h4>
                <p>This is an open study, available to anyone over the age of 18 who is willing to participate.</p>

                <h4>Do I have to take part?</h4>
                <p>
                    Participation in the study is voluntary. If you do decide to take part, you can discontinue participation at any
                    time during the study without needing to give a reason. All data recorded as part of the study is anonymous and you
                    will not be asked to provide any personally identifiable information. Due to the anonymity of the data, it will not
                    be possible to withdraw any data that has already been submitted (such as chat transcripts or survey answers). To
                    discontinue participation, simply close this web browser. You can revisit this web page at a later time to continue
                    participation in the study if you so choose.
                </p>

                <h4>What will happen if I take part?</h4>
                <p>
                    You will be asked to play a game that involves exploring a small virtual world and interacting with several
                    non-player characters who inhabit it. The game will take five to ten minutes to complete. Once completed, you will
                    be asked to answer a series of survey questions relating to your experiences while playing the game. The survey will
                    take about five minutes to complete.
                </p>

                <p>
                    Your answers to the survey, as well as the transcripts of your interactions with the characters, are recorded and
                    will be analysed as part of the study.
                </p>

                <h4>What will happen to the data and results?</h4>
                <p>
                    This study is being conducted as part of a post graduate dissertation assignment. The anonymous data collected
                    during this study will be made open access and could be reused in future studies which have been given ethics
                    approval. Direct quotes from the chat transcripts could be used in the dissertation or future studies. Any
                    personally identifiable information unintentionally recorded (such as through chat transcripts) will be manually
                    anonymised or redacted by the research team.
                </p>

                <h4>Who has reviewed the study?</h4>
                <p>This study has been approved by the City, University of London Research Ethics Committee.</p>

                <h4>What if there is a problem?</h4>
                <p>
                    If you have any problems, concerns or questions about this study, you can contact the research team via email
                    (ian.byrne@city.ac.uk). If you remain unhappy and wish to complain formally, you can do this through City's
                    complaints procedure. To complain about the study, you need to phone 020 7040 3040. You can then ask to speak to the
                    Secretary to Senate Research Ethics Committee.
                </p>

                <p>
                    You can also write to the secretary at:

                    <br>Anna Ramberg
                    <br>Research Integrity Manager
                    <br>City, University of London, Northampton Square
                    <br>London, EC1V 0HB
                    <br>Email: Anna.Ramberg.1@city.ac.uk
                </p>

                <h4>Further information and contact details</h4>
                <p>
                    Researcher: Ian Byrne (ian.byrne@city.ac.uk)
                    <br>Supervisor: Dr Alena Denisova (alena.denisova@city.ac.uk)
                </p>

                <p>
                    Thank you for taking the time to read this information sheet. You can view it again at any time via the link at the
                    bottom of the web page.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Okay</button>
            </div>
        </div>
    </div>
</div>

WebApp/Pages/_SurveyModalPartial.cshtml
@using IanByrne.ResearchProject.Shared.Models
@model IanByrne.ResearchProject.Shared.Models.Survey

<div class="modal fade" id="survey" tabindex="-1" role="dialog" aria-labelledby="surveyLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="surveyLabel">Survey</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    Thank you for playing Post Mortem. Please answer the following questions.
                </p>
                <form asp-page-handler="SurveyModalPartial">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input id="SurveyFormCookieId" asp-for="User.CookieId" type="hidden" value="" />
                    <div class="form-group survey-age">
                        <label asp-for="Age"></label> (Optional)
                        <div>
                            <input asp-for="Age" class="form-control" />
                            <span asp-validation-for="Age" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group survey-gender">
                        <label asp-for="Gender"></label> (Optional)
                        <div>
                            <input asp-for="Gender" type="radio" value="0" id="Gender@(Gender.Male)" /> <label style="font-weight:normal;" for="Gender@(Gender.Male)">Male</label>
                        </div>
                        <div>
                            <input asp-for="Gender" type="radio" value="1" id="Gender@(Gender.Female)" /> <label style="font-weight:normal;" for="Gender@(Gender.Female)">Female</label>
                        </div>
                        <div>
                            <input asp-for="Gender" type="radio" value="2" id="Gender@(Gender.Other_NotGiven)" /> <label style="font-weight:normal;" for="Gender@(Gender.Other_NotGiven)">Other or Not Given</label>
                        </div>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q1"></label>
                        <input likert-for="Q1" />
                        <span asp-validation-for="Q1" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q2"></label>
                        <input likert-for="Q2" />
                        <span asp-validation-for="Q2" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q3"></label>
                        <input likert-for="Q3" />
                        <span asp-validation-for="Q3" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q4"></label>
                        <input likert-for="Q4" />
                        <span asp-validation-for="Q4" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q5"></label>
                        <input likert-for="Q5" />
                        <span asp-validation-for="Q5" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q6"></label>
                        <input likert-for="Q6" />
                        <span asp-validation-for="Q6" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q7"></label>
                        <input likert-for="Q7" />
                        <span asp-validation-for="Q7" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q8"></label>
                        <input likert-for="Q8" />
                        <span asp-validation-for="Q8" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q9"></label>
                        <input likert-for="Q9" />
                        <span asp-validation-for="Q9" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q10"></label>
                        <input likert-for="Q10" />
                        <span asp-validation-for="Q10" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q11"></label>
                        <input likert-for="Q11" />
                        <span asp-validation-for="Q11" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q12"></label>
                        <input likert-for="Q12" />
                        <span asp-validation-for="Q12" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q13"></label>
                        <input likert-for="Q13" />
                        <span asp-validation-for="Q13" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q14"></label>
                        <input likert-for="Q14" />
                        <span asp-validation-for="Q14" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q15"></label>
                        <input likert-for="Q15" />
                        <span asp-validation-for="Q15" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q16"></label>
                        <input likert-for="Q16" />
                        <span asp-validation-for="Q16" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q17"></label>
                        <input likert-for="Q17" />
                        <span asp-validation-for="Q17" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q18"></label>
                        <input likert-for="Q18" />
                        <span asp-validation-for="Q18" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q19"></label>
                        <input likert-for="Q19" />
                        <span asp-validation-for="Q19" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q20"></label>
                        <input likert-for="Q20" />
                        <span asp-validation-for="Q20" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q21"></label>
                        <input likert-for="Q21" />
                        <span asp-validation-for="Q21" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q22"></label>
                        <input likert-for="Q22" />
                        <span asp-validation-for="Q22" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q23"></label>
                        <input likert-for="Q23" />
                        <span asp-validation-for="Q23" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q24"></label>
                        <input likert-for="Q24" />
                        <span asp-validation-for="Q24" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q25"></label>
                        <input likert-for="Q25" />
                        <span asp-validation-for="Q25" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q26"></label>
                        <input likert-for="Q26" />
                        <span asp-validation-for="Q26" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q27"></label>
                        <input likert-for="Q27" />
                        <span asp-validation-for="Q27" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q28"></label>
                        <input likert-for="Q28" />
                        <span asp-validation-for="Q28" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q29"></label>
                        <input likert-for="Q29" />
                        <span asp-validation-for="Q29" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q30"></label>
                        <input likert-for="Q30" />
                        <span asp-validation-for="Q30" class="text-danger"></span>
                    </div>
                    <div class="form-group survey-likert">
                        <label asp-for="Q31"></label>
                        <input likert-for="Q31" />
                        <span asp-validation-for="Q31" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>